### PR TITLE
Merge pull request #9 from bcgov/feature/api-spec

### PR DESCRIPTION
**Pull request by pbolduc**
# Description

This PR contains the initial API project. At this point, it is a single ASP.NET Core Web API that serves up an ```/api/users``` and an ```/api/projects``` endpoints ready for elaboration and data.  

It also fixes up missing commets from previous PR

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Running the project from Visual Studio 2019 and executing the Swagger GUI endpoint (https://localhost:44323/swagger/index.html) and hitting the OpenAPI json endpoint (https://localhost:44323/swagger/v1/swagger.json)

image

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## For bcgov contributors:

this PR fixes jira ticket: **put the jira ticket # here**  I do not have Jira access so I cannot look this up at this point.

### CODE REVIEW

**Comment by ChrisHoban** [comment]
This is going from Master to the Feature Branch, do we need a Pull Request for that?

**Comment by akroon3r** [comment]
I think because the revert was closed, master already holds Phil's work from my mis-merge?

**Comment by ChrisHoban** [comment]
Right but my point being that we would want PR Control going upstream to Master but should allow anyone working on a feature branch to pull down from Master at any time

**Comment by pbolduc** [comment]
I have no idea why it says no changes.  I will rebase changes from master and see if there are any changes needed to be merged still

**Pull request closed without merging**
