### PR TITLE
Maltd 364 & 365

### PR DESCRIPTION
**Pull request by sdevalapurkar**
# Description

This PR adds the composite component for the user search (tickets 364 and 365) with the relevant changes integrating the input field and general button base components into this composite one.

JIRA: https://justice.gov.bc.ca/jira/browse/MDYNAMICS-364, https://justice.gov.bc.ca/jira/browse/MDYNAMICS-365

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

1) Default
Screen Shot 2020-01-24 at 4 27 12 PM

2) Valid
Screen Shot 2020-01-24 at 10 28 11 PM

3) Loading
Screen Shot 2020-01-24 at 10 28 19 PM

4) Invalid
Screen Shot 2020-01-24 at 10 28 25 PM

# How Has This Been Tested?

All linting passes, all prettier checks are complete, visual testing on storybook has been done, and jest/enzyme unit tests have been added.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by akroon3r** [comment]
Screenshots look clean at first glance. 💯

**Comment by ChrisHoban** [comment]
Is the IDIR/ stylistic? In some cases when using an IDIR on a system that can accept multiple domains, we use IDIR/ to say "Hey look up this account but in the IDIR domain" in our system we are only going to use that domain so specifying it is actually moot :)

**Comment by akroon3r** [comment]
Might be a small dumb thing, but when I was doing a project in vue and writing jest tests, I found it really hard to test components with divs that had no ids. I noticed a few of those in your PR.

I'm really not a good front end guy, but I just thought I'd engage on that. Do you think it would make things easier to test down the road? Not sure what your experiences are like with jest.

**Comment by sdevalapurkar** [comment]
> Is the IDIR/ stylistic? In some cases when using an IDIR on a system that can accept multiple domains, we use IDIR/ to say "Hey look up this account but in the IDIR domain" in our system we are only going to use that domain so specifying it is actually moot :)

Yeah I just used it for placeholder values for show - no logic has been set to actually enforce that the user types in `IDIR/` at the start of their username :)

**Comment by sdevalapurkar** [comment]
> Might be a small dumb thing, but when I was doing a project in vue and writing jest tests, I found it really hard to test components with divs that had no ids. I noticed a few of those in your PR.
> 
> I'm really not a good front end guy, but I just thought I'd engage on that. Do you think it would make things easier to test down the road? Not sure what your experiences are like with jest.

Hey, yeah I agree with that in general. However, for these base components, I don't think I need ids on the elements because I am able to test all I need to without any ids - also, these ids will be more useful in the higher order components

**Pull request merged**
